# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [2]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1, 2, 3]
l_2 = [4, 5, 6]

print(f"Summation of a regular python list: {l_1 + l_2}")
print(f"Difference of a regular python list: {l_1 - l_2}")

Summation of a regular python list: [1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [15]:
def sum_lists(l1, l2):
    output = []
    for idx in range(len(l1)):
        output.append(l1[idx] + l2[idx])
    return output
    
sum_lists([2, 3, 4], [1, 5, 2])

[2, 15, 8]

In [13]:
sum_lists(l_1, l_2)

[5, 7, 9]

In [14]:
sum_lists([2, 4, 6, 8, 10], [1, 2, 3, 5, 7, 9])

[3, 6, 9, 13, 17]

#### Importing

In [18]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

In [19]:
np

<module 'numpy' from 'C:\\Users\\bstan\\anaconda3\\envs\\intro\\lib\\site-packages\\numpy\\__init__.py'>

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [40]:
arr1 = np.array([5, 10, 15])
arr1

array([ 5, 10, 15])

In [41]:
print(type(arr1))

<class 'numpy.ndarray'>


###### - np.zeros()

In [42]:
# Shape -- np.zeros() has a parameter of "shape" that must be given tuple - (num_rows, num_columns)
arr_zeros = np.zeros((2, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###### - np.ones()

In [43]:
arr_ones = np.ones((2, 4), int)
arr_ones
# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

###### - np.arange()

In [49]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

In [50]:
arr_range = np.arange(10, 20, 2)
arr_range

array([10, 12, 14, 16, 18])

###### - Making Lists into NDArrays

In [51]:
my_list = [1, 5, 8, 9, 34, 45, 63]
arr_list = np.array(my_list)
arr_list

array([ 1,  5,  8,  9, 34, 45, 63])

#### Performing Calculations on NDArrays

###### - Summation

In [64]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum

array([15, 30, 45, 60, 75])

###### - Difference

In [65]:
result_diff = arr_list2 - arr_list1
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [66]:
result_prod = arr_list1 * arr_list2
result_prod

array([  50,  200,  450,  800, 1250])

###### - Division

In [67]:
result_div = arr_list2 / arr_list1
result_div

array([2., 2., 2., 2., 2.])

#### Modulo

In [68]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0], dtype=int32)

#### Floor Division

In [69]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Exponents

In [73]:
result_exp = arr_list1 ** np.array([2, 3, 4, 3, 2])
result_exp

array([   25,  1000, 50625,  8000,   625], dtype=int32)

In [78]:
short_list = np.array([1, 2, 3])
long_list = np.arange(10)

print(short_list)
print(long_list)

short_list + long_list

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


ValueError: operands could not be broadcast together with shapes (3,) (10,) 

#### Numpy Subsetting

In [ ]:
# result3 <= 800
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


In [80]:
print(result_prod)
print(result_prod > 500)

[  50  200  450  800 1250]
[False False False  True  True]


In [82]:
# subset an array with a conditional
result_prod[result_prod > 500]

array([ 800, 1250])

In [86]:
test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings)
print(test_ndStrings[0] == 'B')
print(test_ndStrings[0])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

['Bob' 'Mark' 'Angelica' 'Barb']
False
Bob


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [92]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
print(M)
print(M[1][1])
# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(f"NDArray Structure:\n{ND_M}")
ND_M

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
4
NDArray Structure:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
print(type(ND_M))

<class 'numpy.ndarray'>


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [94]:
print(ND_M[1,1])

4


#### Assigning Values in NDArrays

In [96]:
ND_M[1,1] = 44

ND_M

array([[ 0,  1,  2],
       [ 3, 44,  5],
       [ 6,  7,  8]])

#### Checking NDArray Type

In [98]:
# usind the .dtype property
ND_M.dtype

dtype('int32')

#### Altering NDArray Type

In [106]:
print(ND_M.dtype)
print(ND_M)

changed = ND_M.astype(np.float32)

print(changed.dtype)
print(changed)

int32
[[ 0  1  2]
 [ 3 44  5]
 [ 6  7  8]]
float32
[[ 0.  1.  2.]
 [ 3. 44.  5.]
 [ 6.  7.  8.]]


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [108]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
ND_M.shape

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [109]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

reshaped = ND_M.reshape( (9, 1) )

reshaped

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [44],
       [ 5],
       [ 6],
       [ 7],
       [ 8]])

In [110]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)
reshaped2 = ND_M.reshape( (1, 9) )

reshaped2

array([[ 0,  1,  2,  3, 44,  5,  6,  7,  8]])

In [114]:
# ND_M.reshape((2, 4))

ValueError: cannot reshape array of size 9 into shape (2,4)

#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [115]:
"""
array([[ 0,  1,  2,  3],
   [ 4,  5,  6,  7],
   [ 8,  9, 10, 11],
   [12, 13, 14, 15]])
"""
answer = np.arange(16).reshape((4, 4))
answer

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [123]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print(my_list[::-1])

[8, 7, 6, 5, 4, 3, 2, 1]


In [134]:
print('Setting Matrix')
M = np.zeros((6, 6))
print('Before Assignment:')
print(M)

# Set the first column to 1
M[:, 0] = 1
print("\nAfter assigning 1 to first column:")
print(M)

# Set rows 3 and 4 to be 5
M[2:4, :] = 5
print("\nAfter assigning 5 to rows 3 and 4:")
print(M)

# Reset Matrix
M = M * 0
print("\nResetting Matrix:")
print(M)

# Set every other column to 3
M[:, ::2] = 3
print("\nAfter assigning 3 to every other column:")
print(M)

# Set the bottom row to be 1, 2, 3, 4, 5, 6
v = np.arange(1,7)
M[-1, :] = v
print("\nAfter assinging vector to last row:")
print(M)

Setting Matrix
Before Assignment:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

After assigning 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

After assigning 5 to rows 3 and 4:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

Resetting Matrix:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

After assigning 3 to every other column:
[[3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]]

After assinging vector to last row:
[[3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [3. 0. 3. 0. 3. 0.]
 [1. 2. 3. 4. 5. 6.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [138]:
arr1 = np.arange(9).reshape((3, 3))
print(arr1)

arr2 = np.array([5, 10, 15])
print(arr2)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 5 10 15]


In [139]:
arr3 = arr1 * arr2
print(arr3)

[[  0  10  30]
 [ 15  40  75]
 [ 30  70 120]]


In [142]:
arr4 = np.array([[2, 4, 3], [4, 3, 2], [5, 3, 2]])

arr1 * arr4

array([[ 0,  4,  6],
       [12, 12, 10],
       [30, 21, 16]])

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [149]:
print(result_prod)
print(result_prod > 500)
print(np.where(result_prod > 500))

print(result_prod[np.where(result_prod > 500)])

# Use the where to transform data
result_prod[np.where(result_prod < 500)] = 300
print(result_prod)

[  50  200  450  800 1250]
[False False False  True  True]
(array([3, 4], dtype=int64),)
[ 800 1250]
[ 300  300  300  800 1250]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [222]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.8822586783592099
Here is a random number between 0 and 1 Million: 720485.6798908623
Here are 5 random numbers between 0 and 10: [9.07981071 9.40105171 5.75715021 5.08506642 7.25925048]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[9.34045819 7.53520078 6.07767176]
 [8.89666569 2.87906434 7.90102384]
 [8.99127309 1.15297403 9.27655784]]


In [281]:
np.random.randint(10, 15, (4,4))

array([[10, 11, 12, 14],
       [12, 10, 11, 12],
       [10, 14, 11, 11],
       [13, 11, 12, 11]])

## Working With CSV's

#### Imports

In [282]:
import csv

#### Reading a CSV

In [286]:
# Creating Function to open and read CSV data
def open_csv(filename, d=','):
    # Create empty list that will eventually hold all data
    data = []
    
    # Open the file
    with open(filename) as marathon_data:
        # Read the file with the csv reader -> Reader Object
        marathon_reader = csv.reader(marathon_data, delimiter=d)
        
        # Loop over the reader and append each row to data list
        for row in marathon_reader:
            data.append(row)
            
    # return data list after file has been closed
    return data


In [287]:
marathon_17 = open_csv('./boston_marathon2017_edited.csv')

print(marathon_17[:5])

[['10K', '15K', '20K', '25K', '30K', '35K', '40K', '5K', 'Age', 'Bib', 'Overall Time in Seconds', 'Citizenship', 'Male Average Times', 'Females Average Times', 'City', 'Country', 'Division', 'Gender', 'Half', 'M/F', 'Name', 'Number of Records', 'Official Time', 'Overall', 'Pace', 'State'], ['12/30/1899 12:30:28 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:02:53 AM', '12/30/1899 12:15:25 AM', '24', '11', '7777', 'KEN', '7777', '', 'Keringet', 'KEN', '1', '1', '12/30/1899 1:04:35 AM', 'M', 'Kirui, Geoffrey', '1', '12/30/1899 2:09:37 AM', '1', '12/30/1899 12:04:57 AM', ''], ['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', 

#### Loading a CSV's Data 

In [304]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



# instead of loading csv normally, let's load it into a numpy array to calculate results on
def np_read_csv(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names=True, dtype=DATATYPES)
    return data


bs17 = np_read_csv('./redsox_2017_hitting.txt')
bs17

array([( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14, 3, 0, 1, 0),
       ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14, 6, 0, 5, 6),
       ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11, 2, 2, 4, 4),
       ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17, 6, 0, 2, 6),
       ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34,  63, 14, 0, 10,  30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5, 0, 0, 0, 3),
       ( 6, b'LF', b'Andrew Benintendi', 22, 151, 658, 573,  84, 155, 26, 1, 20,  90, 20, 5, 70, 112, 0.271, 0.352, 0.424, 0.776, 102, 243, 16, 6, 1, 8, 7),
       ( 7, b'CF', b'Jackie Bradley Jr.', 27, 133, 541, 482,  58, 118, 

In [305]:
print(type(bs17))
print(bs17.dtype)

<class 'numpy.ndarray'>
[('Rk', '<i4'), ('Pos', 'S25'), ('Name', 'S25'), ('Age', '<i4'), ('G', '<i4'), ('PA', '<i4'), ('AB', '<i4'), ('R', '<i4'), ('H', '<i4'), ('2B', '<i4'), ('3B', '<i4'), ('HR', '<i4'), ('RBI', '<i4'), ('SB', '<i4'), ('CS', '<i4'), ('BB', '<i4'), ('SO', '<i4'), ('BA', '<f4'), ('OBP', '<f4'), ('SLG', '<f4'), ('OPS', '<f4'), ('OPS_1', '<i4'), ('TB', '<i4'), ('GDP', '<i4'), ('HBP', '<i4'), ('SH', '<i4'), ('SF', '<i4'), ('IBB', '<i4')]


In [307]:
names = bs17['Name']
print(names)
print(type(names))

[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]
<class 'numpy.ndarray'>


In [309]:
hits = bs17['H']
print(hits)
total_hits = sum(hits)
print(total_hits)

[ 94 125 119 156  63 155 118 166 120  61  57  36  53  28  24  21  20  15
  16   9   1   1   1]
1459


#### Summing the top 5 hitters for HR's

In [319]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all the player names into a variable
# Step 3: Create a new empty list for decoded names
# Step 4: Loop through and decode each name and append to new list
# Step 5: Line up our player names with our hr data [(player, number_of_hr), (player2, number_of_hr),...]
# Step 6: Sort values based on number of home runs
# Step 7: Slice list to first 5

# Step 1
all_home_runs = bs17['HR']
# print(all_home_runs)

# Step 2
all_players = bs17['Name']
# print(all_players)

# Step 3
clean_names = []

# Step 4
for name in all_players:
    decoded_name = name.decode('utf-8')
    clean_names.append(decoded_name)
# print(clean_names)

# Step 5
zipped_values = [(clean_names[i], all_home_runs[i]) for i in range(len(clean_names))]
# print(zipped_values)

# Step 6
sorted_hrs = sorted(zipped_values, key=lambda player: player[1], reverse=True)
# print(sorted_hrs)

# Step 7
top_5 = sorted_hrs[:5]
print(top_5)

[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>